### ISSUE TITLE
NavTree is not being updated once we create new classes

### ISSUE THREAD

**Issue by erickpintor** [faunadb/dashboard#65]

**Comment by erickpintor** [comment]
It seems like now that @marrony has refactored the classes and indexes to a redux store we have all the tools in place to make the nav tree more consistent with the application state.

**Comment by jchris** [comment]
It used to be that that what what the `schemaBump` nonce state / prop was for. So that on making any schema changes you just touch that, and the navtree re-queries itself. But now it doesn't run the query when unrelated state changes, so we need a real fix instead of my old hack. But we can remove `bumpSchema` in the process.

**Comment by erickpintor** [comment]
That's where I'm heading to :)
